// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELiNqgIHGKV8E2u2Dc6Pg2qrDOt8O4Z8',
    appId: '1:451447385833:web:7544f6f2f86148e2790a78',
    messagingSenderId: '451447385833',
    projectId: 'hudai-ddc43',
    authDomain: 'hudai-ddc43.firebaseapp.com',
    storageBucket: 'hudai-ddc43.firebasestorage.app',
    measurementId: 'G-N8CYDWPKCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf8lBvcm7XsGNiCETMNjRWkIo_xiyII7g',
    appId: '1:451447385833:android:248418ef3792cca0790a78',
    messagingSenderId: '451447385833',
    projectId: 'hudai-ddc43',
    storageBucket: 'hudai-ddc43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjRX4Eu1V-I6q-m2-adtzL3M_BqSPNyU',
    appId: '1:451447385833:ios:181f87ae4456eb2d790a78',
    messagingSenderId: '451447385833',
    projectId: 'hudai-ddc43',
    storageBucket: 'hudai-ddc43.firebasestorage.app',
    iosBundleId: 'com.example.hudai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjRX4Eu1V-I6q-m2-adtzL3M_BqSPNyU',
    appId: '1:451447385833:ios:181f87ae4456eb2d790a78',
    messagingSenderId: '451447385833',
    projectId: 'hudai-ddc43',
    storageBucket: 'hudai-ddc43.firebasestorage.app',
    iosBundleId: 'com.example.hudai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELiNqgIHGKV8E2u2Dc6Pg2qrDOt8O4Z8',
    appId: '1:451447385833:web:0c33660a554d8e0a790a78',
    messagingSenderId: '451447385833',
    projectId: 'hudai-ddc43',
    authDomain: 'hudai-ddc43.firebaseapp.com',
    storageBucket: 'hudai-ddc43.firebasestorage.app',
    measurementId: 'G-NXMRZVMC8E',
  );
}
